language: php
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/soap-client -vvv generate config/config.yml src/Container --dest-class=WeatherWS/Container/SoapContainer
  - php bin/demo.php
