soap_client:
  #  alternative_endpoints:
  #    service:
  #      port: http://localhost:8080
  namespaces:
    'http://tempuri.org/': 'Calculator'

  destinations_php:
    'Calculator': src/Calculator

  destinations_jms:
    'Calculator': metadata/Calculator
  metadata:
    'http://www.dneonline.com/calculator.asmx?WSDL': ~
